name: Build ChimeraOS Linux Kernel

on:
  push:
    branches: [ ruineka-build ]
  workflow_dispatch:

env:
  PKGDEST: "/tmp/linux-chimeraos"

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    outputs:
      full_version: ${{ steps.build-kernel-package.full_version }}

    container: archlinux:base-devel

    steps:
      - uses: actions/checkout@v3
      - name: Create build user
        run: |
          useradd -m build
          cp -vR linux /home/build/linux
          chown -vR build /home/build/linux
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm bc cpio git pahole python kmod
      - name: Build linux-chimeraos package
        id: build-kernel-package
        shell: bash
        run: |
          su build bash -c "cd /home/build/linux && MAKEFLAGS=-j4 makepkg"
          . /home/build/linux/PKGBUILD
          full_version=${pkgver}-${pkgrel}
          echo "::set-output name=full_version::$full_version"
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-chimeraos-${{ steps.build-kernel-package.full_version }}
          path: |
            ${{ env.PKGDEST }}/*.pkg.tar.zst
          if-no-files-found: error

  make-release:
    runs-on: ubuntu-latest
    needs: [build-kernel]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.PKGDEST }}

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: linux-chimeraos-${{ needs.build-kernel.outputs.full_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.PKGDEST }}/linux-chimeraos-*/*.pkg.tar.zst
